[package]
name = "pollapo"
version = "0.0.2"
edition = "2021"
description = "pollapo rust impelmentation"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_zip = "0.0.9"
clap = { version = "4.0.23", features = ["derive"] }
piz = "0.5.1"
reqwest = "0.11.13"
serde = { version = "1.0.147", features = ["derive"] }
serde_yaml = "0.9.14"
shellexpand = "2.1.2"
futures = "0.3.25"

[dev-dependencies]
tokio-test = "*"
serial_test = { version = "*", features = ["file_locks"] }
