name: "Test"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "[SETUP] Checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - name: "[SETUP] Cache"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: "[SETUP] Rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "[TEST] Run test"
        run: cargo test

